### PR TITLE
Develop debug map center

### LINKED ISSUE #876: fix incorrect centering for map on home click
**Describe the bug**
On home icon click, the map centers on incorrect location.

**To Reproduce**
1. Load app
2. Note map center
3. Click on home icon
4. Note map center changes to "phantom address"

**Expected behavior**
Expect the map center to be same on home click vs initial page load / map load

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This happens in the `develop` branch, which is preventing us from deploying to `production` to fix #673

### PR DESCRIPTION
**Pull request by nickvisut**
# Description

This PR fixes map centering and various regressions. Additionally, it fixes a few other issues that were discovered:
- address setting state synchronously in useEffect patterns

Closes #876

## Type of changes
- (x) Bugfix
- (x) Chore
- ( ) New Feature

## Testing
- (x) I added automated tests - updated existing tests
- ( ) I think tests are unnecessary

## How to test

test that autocomplete and all usual functionality still works

## Clean commits
- ( ) I plan to Squash and Merge
- (x) My commit history is clean¹
  ¹ [_described here_](../blob/develop/README.md#keep-your-commit-history-clean)

### CODE REVIEW

File: app/components/mobile-report-hazards.tsx [hunk 1]
```diff
@@ -58,7 +58,8 @@ const MobileReportHazards = ({
           </Button>
         </Menu.Trigger>
         <Portal>
-          <Menu.Positioner>
+          <Menu.Positioner hideFrom="md">
```
Comment (nickvisut) [inline app/components/mobile-report-hazards.tsx]: remove hideFrom

File: app/components/address-mapper.tsx [hunk 2]
```diff
@@ -211,37 +205,47 @@ const AddressMapper: React.FC<AddressMapperProps> = ({
...
+        position={{ base: "relative", md: "static" }}
+        alignItems={{ base: "stretch", md: "start" }}
+        display={{ base: "block", md: "flex" }}
       >
-        {currentView === "desktop" ? (
-          <Box h="full" overflowY={{ base: "visible", sm: "auto" }}>
-            <ReportHazards
-              addressHazardData={addressHazardData}
+        {!md ? (
+          <Box hideFrom="md" zIndex="docked" top="0" position="absolute">
```
Comment (nickvisut) [inline app/components/address-mapper.tsx]: remove hideFrom

File: app/components/address-mapper.tsx [hunk 3]
```diff
@@ -211,37 +205,47 @@ const AddressMapper: React.FC<AddressMapperProps> = ({
...
+            />
           </Box>
-        ) : currentView === "mobile" ? (
-          <Box zIndex="docked" top="0" position="absolute">
-            <MobileReportHazards
-              showHazards={showHazards}
-              addressHazardData={addressHazardData}
+        ) : (
+          <Box
+            hideBelow="md"
```
Comment (nickvisut) [inline app/components/address-mapper.tsx]: remove hideBelow

File: app/components/search-bar.tsx [hunk 4]
```diff
@@ -69,22 +69,14 @@ const SearchBar = ({
...
-  };
+  // TODO: consider also capturing/updating address on submit OR using first autocomplete suggestion; see file://./../snippets.md#geocode-on-search for details.
 
   const handleSuggest = (res: AddressAutofillSuggestionResponse) => {
     setSuggestionsAvailable(res.suggestions.length > 0);
   };
 
   return (
-    <chakra.form position={"relative"} onSubmit={onSubmit}>
+    <chakra.form position={"relative"}>
```
[the remark this answers is not in the document]
Comment (nickvisut) [reply app/components/search-bar.tsx:79]: may address this in a later issue

**Review by nutanp — APPROVED** [review]

**Review by nutanp — APPROVED** [review]
Did code review with Nick and approving all changes .

File: app/components/map.tsx [hunk 5]
```diff
@@ -173,14 +169,57 @@ const Map: React.FC<MapProps> = ({
...
+          // no address, so remove map marker if it exists
+          if (markerRef.current) {
+            console.log(
+              "removing markerRef.current marker from map and setting to null"
+            );
+            markerRef.current?.remove();
+            markerRef.current = null;
+          }
+        }
+        map.panTo(center, { duration: 750 }); // pan to new center
```
[the remark this answers is not in the document]
Comment (nickvisut) [reply app/components/map.tsx]: fixed by only panning if the map center is different
